// Generates the campaign levels 4..30 as real Tiled `.tmx` files plus the
// matching `LevelInfo` catalog entries.
//
//   dart run tool/generate_levels.dart
//
// Levels 1-3 are hand-authored and left untouched. Everything this script emits
// is a normal `.tmx` you can still open in Tiled and tweak by hand — rerunning
// the script overwrites those tweaks, so pull a level out of the generated range
// (rename it, add a handcrafted catalog entry) if you want to keep edits.
//
// Tuning lives in two places: [_templates] (path + tower-spot shapes) and
// [_LevelSpec.forLevel] (the difficulty curve).

import 'dart:io';
import 'dart:math' as math;

const int kFirstGenerated = 4;
const int kLastGenerated = 30;

const int gridCols = 20;
const int gridRows = 12;
const int cellSize = 48;

void main() {
  final levelsDir = Directory('assets/levels');
  if (!levelsDir.existsSync()) {
    stderr.writeln('run me from the package root (no assets/levels/)');
    exit(1);
  }

  final catalog = StringBuffer();
  for (var level = kFirstGenerated; level <= kLastGenerated; level++) {
    final spec = _LevelSpec.forLevel(level);
    final shape = _shapeForLevel(level);
    final file = File('assets/levels/${_levelId(level)}.tmx');
    file.writeAsStringSync(_tmx(level, spec, shape));
    stdout.writeln('wrote ${file.path}  '
        '(${spec.waveCount} waves, hp ${spec.enemyHp.round()})');

    catalog.writeln('  LevelInfo(');
    catalog.writeln("    id: '${_levelId(level)}',");
    catalog.writeln("    tmxAsset: 'assets/levels/${_levelId(level)}.tmx',");
    catalog.writeln("    title: '${_escape(_title(level))}',");
    catalog.writeln("    tagline: '${_escape(spec.tagline)}',");
    catalog.writeln('  ),');
  }

  File('lib/features/game/data/levels/generated_levels.dart').writeAsStringSync(
    "// GENERATED by tool/generate_levels.dart — do not edit by hand.\n"
    "// Run `dart run tool/generate_levels.dart` to regenerate.\n\n"
    "import '../../domain/models/level_info.dart';\n\n"
    "/// Campaign levels $kFirstGenerated..$kLastGenerated, procedurally generated.\n"
    'const List<LevelInfo> kGeneratedLevels = <LevelInfo>[\n'
    '$catalog'
    '];\n',
  );
  stdout.writeln('wrote lib/features/game/data/levels/generated_levels.dart');
}

String _levelId(int level) => 'level_${level.toString().padLeft(2, '0')}';

// --- difficulty curve -------------------------------------------------------

class _LevelSpec {
  _LevelSpec({
    required this.startingLives,
    required this.startingGold,
    required this.timeBetweenWaves,
    required this.enemyHp,
    required this.enemySpeed,
    required this.enemyGold,
    required this.waveCount,
    required this.waves,
    required this.tagline,
  });

  final int startingLives;
  final int startingGold;
  final double timeBetweenWaves;
  final double enemyHp;
  final double enemySpeed;
  final int enemyGold;
  final int waveCount;
  final String waves;
  final String tagline;

  factory _LevelSpec.forLevel(int level) {
    final l = level.toDouble();

    // HP: gentle at first, then a quadratic ramp so towers stay relevant.
    final hp = 24 + (l - 1) * 10 + (l - 1) * (l - 1) * 0.5;
    final speed = math.min(55 + l * 0.8, 96).toDouble();
    final gold = (7 + level ~/ 4);
    final waveCount = (6 + (l - 4) * 0.45).round().clamp(6, 20);

    final waves = <String>[];
    for (var w = 1; w <= waveCount; w++) {
      final isLast = w == waveCount;
      final count = (5 + w + level ~/ 3) + (isLast ? 4 : 0);
      final interval =
          (0.85 - l * 0.013 - w * 0.02).clamp(0.22, 0.9).toStringAsFixed(2);
      // Every 4th wave (and the finale) comes as a tighter double burst.
      if (isLast || w % 4 == 0) {
        final half = (count / 2).ceil();
        waves.add('$half@$interval+${count - half}@${(double.parse(interval) *
            1.6).clamp(0.3, 1.2).toStringAsFixed(2)}');
      } else {
        waves.add('$count@$interval');
      }
    }

    return _LevelSpec(
      startingLives: 20 + (level ~/ 10) * 2,
      startingGold: 100 + level * 3,
      timeBetweenWaves: 3,
      enemyHp: hp,
      enemySpeed: speed,
      enemyGold: gold,
      waveCount: waveCount,
      waves: waves.join(';'),
      tagline: _tagline(level, waveCount),
    );
  }
}

String _tagline(int level, int waveCount) {
  if (level <= 8) {
    return 'Sức ép tăng dần — $waveCount đợt heo, đặt tháp sớm và chắc.';
  }
  if (level <= 16) {
    return 'Heo dày mình hơn. Ghép Đại Bác với Tên Lửa để dọn cả đàn.';
  }
  if (level <= 24) {
    return '$waveCount đợt liên hoàn, có nhịp dồn kép. Giữ vàng cho nâng cấp.';
  }
  return 'Cửa ải cuối: heo thép, tới như thác. Không được rò một con.';
}

// --- path / tower-spot shapes ---------------------------------------------

class _Shape {
  const _Shape(this.path, this.spots);
  final List<List<int>> path;
  final List<List<int>> spots;
}

// Six base shapes on the 20x12 grid (cell coords; first/last points sit off the
// edge so pigs march on and off screen). Each generated level picks one and
// applies a mirror, giving 24 distinct layouts before anything repeats.
const List<_Shape> _templates = <_Shape>[
  _Shape(
    <List<int>>[
      [-1, 2], [3, 2], [3, 9], [9, 9], [9, 3], [15, 3], [15, 9], [20, 9],
    ],
    <List<int>>[
      [2, 4], [5, 7], [6, 10], [8, 6], [11, 4], [12, 1], [14, 6], [17, 7],
      [13, 10],
    ],
  ),
  _Shape(
    <List<int>>[
      [-1, 6], [2, 6], [2, 2], [7, 2], [7, 9], [12, 9], [12, 4], [16, 4],
      [16, 10], [20, 10],
    ],
    <List<int>>[
      [1, 4], [4, 4], [5, 1], [9, 5], [6, 7], [10, 7], [14, 6], [14, 2],
      [18, 8],
    ],
  ),
  _Shape(
    <List<int>>[
      [-1, 1], [4, 1], [4, 6], [1, 6], [1, 10], [9, 10], [9, 3], [13, 3],
      [13, 8], [17, 8], [17, 2], [20, 2],
    ],
    <List<int>>[
      [2, 3], [6, 3], [6, 8], [3, 8], [11, 7], [7, 6], [15, 5], [15, 10],
      [18, 4],
    ],
  ),
  _Shape(
    <List<int>>[
      [-1, 1], [18, 1], [18, 5], [1, 5], [1, 9], [20, 9],
    ],
    <List<int>>[
      [3, 3], [9, 3], [15, 3], [4, 7], [10, 7], [16, 7], [6, 11], [12, 11],
      [17, 3],
    ],
  ),
  _Shape(
    <List<int>>[
      [-1, 6], [10, 6], [10, 1], [3, 1], [3, 10], [17, 10], [17, 4], [11, 4],
      [11, 8], [20, 8],
    ],
    <List<int>>[
      [7, 3], [1, 4], [6, 8], [9, 9], [14, 7], [15, 6], [19, 6], [2, 11],
      [8, 2],
    ],
  ),
  _Shape(
    <List<int>>[
      [-1, 10], [4, 10], [4, 4], [8, 4], [8, 10], [12, 10], [12, 4], [16, 4],
      [16, 10], [20, 10],
    ],
    <List<int>>[
      [2, 7], [6, 7], [6, 2], [10, 7], [10, 2], [14, 7], [14, 2], [18, 7],
      [18, 11],
    ],
  ),
];

_Shape _shapeForLevel(int level) {
  // +7 so the first generated level doesn't land on template 0 identity
  // (which is Level 1's exact shape).
  final n = level - kFirstGenerated + 7;
  final base = _templates[n % _templates.length];
  final mirror = (n ~/ _templates.length) % 4; // 0..3
  final flipX = mirror == 1 || mirror == 3;
  final flipY = mirror == 2 || mirror == 3;

  List<int> t(List<int> p) => <int>[
        flipX ? (gridCols - 1 - p[0]) : p[0],
        flipY ? (gridRows - 1 - p[1]) : p[1],
      ];

  return _Shape(
    base.path.map(t).toList(),
    base.spots.map(t).toList(),
  );
}

// --- .tmx emitter --------------------------------------------------------

int _px(int cell) => ((cell + 0.5) * cellSize).round();

String _tmx(int level, _LevelSpec spec, _Shape shape) {
  final polyline =
      shape.path.map((p) => '${_px(p[0])},${_px(p[1])}').join(' ');

  final spots = StringBuffer();
  var id = 2;
  for (final s in shape.spots) {
    spots.writeln(
        '  <object id="${id++}" x="${_px(s[0])}" y="${_px(s[1])}"><point/></object>');
  }

  return '''<?xml version="1.0" encoding="UTF-8"?>
<map version="1.10" tiledversion="1.11.0" orientation="orthogonal" renderorder="right-down" width="$gridCols" height="$gridRows" tilewidth="$cellSize" tileheight="$cellSize" infinite="0" nextlayerid="3" nextobjectid="${id + 1}">
 <properties>
  <property name="title" value="${_escape(_title(level))}"/>
  <property name="background" value="game/level_01_background.png"/>
  <property name="startingLives" type="int" value="${spec.startingLives}"/>
  <property name="startingGold" type="int" value="${spec.startingGold}"/>
  <property name="timeBetweenWaves" type="float" value="${spec.timeBetweenWaves}"/>
  <property name="towers" value="arrow,cannon,flamingArrow"/>
  <property name="enemyHp" type="float" value="${spec.enemyHp.round()}"/>
  <property name="enemySpeed" type="float" value="${spec.enemySpeed.round()}"/>
  <property name="enemyGold" type="int" value="${spec.enemyGold}"/>
  <property name="enemyLives" type="int" value="1"/>
  <property name="waves" value="${spec.waves}"/>
 </properties>
 <objectgroup id="1" name="path">
  <object id="1" name="river" x="0" y="0">
   <polyline points="$polyline"/>
  </object>
 </objectgroup>
 <objectgroup id="2" name="buildspots">
$spots </objectgroup>
</map>
''';
}

// --- names --------------------------------------------------------------

const List<String> _names = <String>[
  'Dòng xoáy', 'Bến vắng', 'Thác Bạc', 'Kênh Đôi', 'Vũng Lầy', 'Cầu Gãy',
  'Rừng Ngập', 'Đầm Sen', 'Vịnh Cạn', 'Suối Đá', 'Ghềnh Thác', 'Chợ Nổi',
  'Cồn Cát', 'Lạch Sâu', 'Đập Tràn', 'Cửa Cống', 'Bãi Sậy', 'Xẻo Quýt',
  'Rạch Chằng', 'Ngã Bảy', 'Hồ Gió', 'Vực Xoáy', 'Doi Đất', 'Bàu Sấu',
  'Cửa Đại', 'Sóng Thần', 'Trùng Khơi',
];

String _title(int level) {
  final name = _names[(level - kFirstGenerated) % _names.length];
  return 'Màn $level — $name';
}

String _escape(String s) => s
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
