// GENERATED by tool/generate_levels.dart — do not edit by hand.
// Run `dart run tool/generate_levels.dart` to regenerate.

import '../../domain/models/level_info.dart';

/// Campaign levels 4..30, procedurally generated.
const List<LevelInfo> kGeneratedLevels = <LevelInfo>[
  LevelInfo(
    id: 'level_04',
    tmxAsset: 'assets/levels/level_04.tmx',
    title: 'Màn 4 — Dòng xoáy',
    tagline: 'Sức ép tăng dần — 6 đợt heo, đặt tháp sớm và chắc.',
  ),
  LevelInfo(
    id: 'level_05',
    tmxAsset: 'assets/levels/level_05.tmx',
    title: 'Màn 5 — Bến vắng',
    tagline: 'Sức ép tăng dần — 6 đợt heo, đặt tháp sớm và chắc.',
  ),
  LevelInfo(
    id: 'level_06',
    tmxAsset: 'assets/levels/level_06.tmx',
    title: 'Màn 6 — Thác Bạc',
    tagline: 'Sức ép tăng dần — 7 đợt heo, đặt tháp sớm và chắc.',
  ),
  LevelInfo(
    id: 'level_07',
    tmxAsset: 'assets/levels/level_07.tmx',
    title: 'Màn 7 — Kênh Đôi',
    tagline: 'Sức ép tăng dần — 7 đợt heo, đặt tháp sớm và chắc.',
  ),
  LevelInfo(
    id: 'level_08',
    tmxAsset: 'assets/levels/level_08.tmx',
    title: 'Màn 8 — Vũng Lầy',
    tagline: 'Sức ép tăng dần — 8 đợt heo, đặt tháp sớm và chắc.',
  ),
  LevelInfo(
    id: 'level_09',
    tmxAsset: 'assets/levels/level_09.tmx',
    title: 'Màn 9 — Cầu Gãy',
    tagline: 'Heo dày mình hơn. Ghép Đại Bác với Tên Lửa để dọn cả đàn.',
  ),
  LevelInfo(
    id: 'level_10',
    tmxAsset: 'assets/levels/level_10.tmx',
    title: 'Màn 10 — Rừng Ngập',
    tagline: 'Heo dày mình hơn. Ghép Đại Bác với Tên Lửa để dọn cả đàn.',
  ),
  LevelInfo(
    id: 'level_11',
    tmxAsset: 'assets/levels/level_11.tmx',
    title: 'Màn 11 — Đầm Sen',
    tagline: 'Heo dày mình hơn. Ghép Đại Bác với Tên Lửa để dọn cả đàn.',
  ),
  LevelInfo(
    id: 'level_12',
    tmxAsset: 'assets/levels/level_12.tmx',
    title: 'Màn 12 — Vịnh Cạn',
    tagline: 'Heo dày mình hơn. Ghép Đại Bác với Tên Lửa để dọn cả đàn.',
  ),
  LevelInfo(
    id: 'level_13',
    tmxAsset: 'assets/levels/level_13.tmx',
    title: 'Màn 13 — Suối Đá',
    tagline: 'Heo dày mình hơn. Ghép Đại Bác với Tên Lửa để dọn cả đàn.',
  ),
  LevelInfo(
    id: 'level_14',
    tmxAsset: 'assets/levels/level_14.tmx',
    title: 'Màn 14 — Ghềnh Thác',
    tagline: 'Heo dày mình hơn. Ghép Đại Bác với Tên Lửa để dọn cả đàn.',
  ),
  LevelInfo(
    id: 'level_15',
    tmxAsset: 'assets/levels/level_15.tmx',
    title: 'Màn 15 — Chợ Nổi',
    tagline: 'Heo dày mình hơn. Ghép Đại Bác với Tên Lửa để dọn cả đàn.',
  ),
  LevelInfo(
    id: 'level_16',
    tmxAsset: 'assets/levels/level_16.tmx',
    title: 'Màn 16 — Cồn Cát',
    tagline: 'Heo dày mình hơn. Ghép Đại Bác với Tên Lửa để dọn cả đàn.',
  ),
  LevelInfo(
    id: 'level_17',
    tmxAsset: 'assets/levels/level_17.tmx',
    title: 'Màn 17 — Lạch Sâu',
    tagline: '12 đợt liên hoàn, có nhịp dồn kép. Giữ vàng cho nâng cấp.',
  ),
  LevelInfo(
    id: 'level_18',
    tmxAsset: 'assets/levels/level_18.tmx',
    title: 'Màn 18 — Đập Tràn',
    tagline: '12 đợt liên hoàn, có nhịp dồn kép. Giữ vàng cho nâng cấp.',
  ),
  LevelInfo(
    id: 'level_19',
    tmxAsset: 'assets/levels/level_19.tmx',
    title: 'Màn 19 — Cửa Cống',
    tagline: '13 đợt liên hoàn, có nhịp dồn kép. Giữ vàng cho nâng cấp.',
  ),
  LevelInfo(
    id: 'level_20',
    tmxAsset: 'assets/levels/level_20.tmx',
    title: 'Màn 20 — Bãi Sậy',
    tagline: '13 đợt liên hoàn, có nhịp dồn kép. Giữ vàng cho nâng cấp.',
  ),
  LevelInfo(
    id: 'level_21',
    tmxAsset: 'assets/levels/level_21.tmx',
    title: 'Màn 21 — Xẻo Quýt',
    tagline: '14 đợt liên hoàn, có nhịp dồn kép. Giữ vàng cho nâng cấp.',
  ),
  LevelInfo(
    id: 'level_22',
    tmxAsset: 'assets/levels/level_22.tmx',
    title: 'Màn 22 — Rạch Chằng',
    tagline: '14 đợt liên hoàn, có nhịp dồn kép. Giữ vàng cho nâng cấp.',
  ),
  LevelInfo(
    id: 'level_23',
    tmxAsset: 'assets/levels/level_23.tmx',
    title: 'Màn 23 — Ngã Bảy',
    tagline: '15 đợt liên hoàn, có nhịp dồn kép. Giữ vàng cho nâng cấp.',
  ),
  LevelInfo(
    id: 'level_24',
    tmxAsset: 'assets/levels/level_24.tmx',
    title: 'Màn 24 — Hồ Gió',
    tagline: '15 đợt liên hoàn, có nhịp dồn kép. Giữ vàng cho nâng cấp.',
  ),
  LevelInfo(
    id: 'level_25',
    tmxAsset: 'assets/levels/level_25.tmx',
    title: 'Màn 25 — Vực Xoáy',
    tagline: 'Cửa ải cuối: heo thép, tới như thác. Không được rò một con.',
  ),
  LevelInfo(
    id: 'level_26',
    tmxAsset: 'assets/levels/level_26.tmx',
    title: 'Màn 26 — Doi Đất',
    tagline: 'Cửa ải cuối: heo thép, tới như thác. Không được rò một con.',
  ),
  LevelInfo(
    id: 'level_27',
    tmxAsset: 'assets/levels/level_27.tmx',
    title: 'Màn 27 — Bàu Sấu',
    tagline: 'Cửa ải cuối: heo thép, tới như thác. Không được rò một con.',
  ),
  LevelInfo(
    id: 'level_28',
    tmxAsset: 'assets/levels/level_28.tmx',
    title: 'Màn 28 — Cửa Đại',
    tagline: 'Cửa ải cuối: heo thép, tới như thác. Không được rò một con.',
  ),
  LevelInfo(
    id: 'level_29',
    tmxAsset: 'assets/levels/level_29.tmx',
    title: 'Màn 29 — Sóng Thần',
    tagline: 'Cửa ải cuối: heo thép, tới như thác. Không được rò một con.',
  ),
  LevelInfo(
    id: 'level_30',
    tmxAsset: 'assets/levels/level_30.tmx',
    title: 'Màn 30 — Trùng Khơi',
    tagline: 'Cửa ải cuối: heo thép, tới như thác. Không được rò một con.',
  ),
];
